### ISSUE TITLE
Bot requires a .json file and while youtube data is downloaded in .html

### ISSUE THREAD

**Issue by KaustubhRai** [flofriday/youtube-data#3]
The link that you gave to download youtube data, it downloads the two files "search-history" and "watch-history" in .html format. The bot requires me to first convert that .html to .json and then forward it to the bot.

**Comment by flofriday** [comment]
Hey, here is a Guide a wrote, on how to download the data (in json, Step 3):
https://www.github.com/flofriday/youtube-data/tree/master/Download_Guide.md 

There is no need to convert the html to json manually, just redownload the data in the correct format.
